// Mock data for Super Admin - all tenants in the system
export const mockTenants = [
  {
    id: "t1",
    companyName: "Arçelik A.Ş.",
    taxNumber: "7240042696",
    contactName: "Mehmet Yılmaz",
    contactEmail: "m.yilmaz@arcelik.com",
    contactPhone: "+90 212 555 0101",
    address: "Karaağaç Cad. No:2-6 Sütlüce, Beyoğlu / İstanbul",
    agentStatus: "online",
    agentVersion: "2.4.1",
    agentLastSeen: "2026-03-05T08:30:00",
    logoErpDb: "ARCELIK_PROD",
    logoErpVersion: "2024.2",
    plan: "Enterprise",
    createdAt: "2024-01-15T10:00:00",
    isActive: true,
    stats: { totalOrders: 15420, successRate: 98.7, pendingJobs: 3 },
  },
  {
    id: "t2",
    companyName: "Koç Sistem A.Ş.",
    taxNumber: "9870012345",
    contactName: "Ayşe Demir",
    contactEmail: "a.demir@kocsistem.com.tr",
    contactPhone: "+90 216 555 0202",
    address: "Nakkaştepe Azizbey Sok. No:1, Kuzguncuk / İstanbul",
    agentStatus: "online",
    agentVersion: "2.4.1",
    agentLastSeen: "2026-03-05T08:28:00",
    logoErpDb: "KOCSISTEM_LIVE",
    logoErpVersion: "2024.2",
    plan: "Business",
    createdAt: "2024-02-20T14:00:00",
    isActive: true,
    stats: { totalOrders: 8750, successRate: 99.1, pendingJobs: 0 },
  },
  {
    id: "t3",
    companyName: "Migros Ticaret A.Ş.",
    taxNumber: "4560078901",
    contactName: "Ali Kaya",
    contactEmail: "a.kaya@migros.com.tr",
    contactPhone: "+90 212 555 0303",
    address: "Turgut Özal Bulvarı No:1, Bağcılar / İstanbul",
    agentStatus: "offline",
    agentVersion: "2.3.8",
    agentLastSeen: "2026-03-04T23:15:00",
    logoErpDb: "MIGROS_ERP",
    logoErpVersion: "2023.3",
    plan: "Enterprise",
    createdAt: "2024-03-10T09:00:00",
    isActive: true,
    stats: { totalOrders: 32100, successRate: 97.2, pendingJobs: 12 },
  },
  {
    id: "t4",
    companyName: "Teknosa İç ve Dış Ticaret A.Ş.",
    taxNumber: "1230056789",
    contactName: "Fatma Şahin",
    contactEmail: "f.sahin@teknosa.com",
    contactPhone: "+90 212 555 0404",
    address: "Saray Mahallesi, Site Yolu Cad. No:5, Ümraniye / İstanbul",
    agentStatus: "online",
    agentVersion: "2.4.0",
    agentLastSeen: "2026-03-05T08:25:00",
    logoErpDb: "TEKNOSA_DB",
    logoErpVersion: "2024.1",
    plan: "Business",
    createdAt: "2024-04-05T11:00:00",
    isActive: true,
    stats: { totalOrders: 6340, successRate: 99.5, pendingJobs: 1 },
  },
  {
    id: "t5",
    companyName: "Hepsiburada.com A.Ş.",
    taxNumber: "7890034512",
    contactName: "Kemal Özkan",
    contactEmail: "k.ozkan@hepsiburada.com",
    contactPhone: "+90 212 555 0505",
    address: "Çobançeşme Bulvarı No:2, Yenibosna / İstanbul",
    agentStatus: "online",
    agentVersion: "2.4.1",
    agentLastSeen: "2026-03-05T08:31:00",
    logoErpDb: "HB_PROD_01",
    logoErpVersion: "2024.2",
    plan: "Enterprise",
    createdAt: "2024-04-20T15:00:00",
    isActive: true,
    stats: { totalOrders: 48920, successRate: 98.9, pendingJobs: 7 },
  },
  {
    id: "t6",
    companyName: "Çiçeksepeti A.Ş.",
    taxNumber: "3210067890",
    contactName: "Zeynep Çelik",
    contactEmail: "z.celik@ciceksepeti.com",
    contactPhone: "+90 212 555 0606",
    address: "Esentepe Mahallesi, Büyükdere Cad. No:199, Şişli / İstanbul",
    agentStatus: "offline",
    agentVersion: "2.3.5",
    agentLastSeen: "2026-03-03T18:00:00",
    logoErpDb: "CICEKSEPETI_ERP",
    logoErpVersion: "2023.2",
    plan: "Starter",
    createdAt: "2024-05-15T10:00:00",
    isActive: false,
    stats: { totalOrders: 2150, successRate: 94.3, pendingJobs: 0 },
  },
];

// Mock integration logs
export const mockLogs = [
  {
    id: "log001",
    tenantId: "t1",
    tenantName: "Arçelik A.Ş.",
    requestId: "REQ-20260305-001",
    type: "ORDER",
    source: "Trendyol API",
    status: "success",
    startedAt: "2026-03-05T08:30:15",
    completedAt: "2026-03-05T08:30:18",
    duration: 2847,
    steps: [
      { name: "API Request Alındı", status: "success", duration: 12 },
      { name: "Payload Doğrulama", status: "success", duration: 45 },
      { name: "Cari Kodu Üretimi", status: "success", duration: 120 },
      { name: "Logo ERP Dönüşümü", status: "success", duration: 890 },
      { name: "Agent'a İletim", status: "success", duration: 1780 },
    ],
    payload: { orderId: "TY-98765432", amount: 4299.99, currency: "TRY" },
    errorMessage: null,
  },
  {
    id: "log002",
    tenantId: "t1",
    tenantName: "Arçelik A.Ş.",
    requestId: "REQ-20260305-002",
    type: "CUSTOMER",
    source: "B2B Portal",
    status: "error",
    startedAt: "2026-03-05T08:25:10",
    completedAt: "2026-03-05T08:25:11",
    duration: 1243,
    steps: [
      { name: "API Request Alındı", status: "success", duration: 10 },
      { name: "Payload Doğrulama", status: "success", duration: 38 },
      { name: "Cari Kodu Üretimi", status: "success", duration: 95 },
      { name: "Logo ERP Dönüşümü", status: "error", duration: 1100 },
      { name: "Agent'a İletim", status: "skipped", duration: 0 },
    ],
    payload: { customerId: "B2B-001234", taxNumber: "1234567890" },
    errorMessage: "Logo ERP: Vergi numarası mükerrer kayıt. (Hata Kodu: ERP-4021)",
  },
  {
    id: "log003",
    tenantId: "t2",
    tenantName: "Koç Sistem A.Ş.",
    requestId: "REQ-20260305-003",
    type: "INVOICE",
    source: "E-Fatura API",
    status: "success",
    startedAt: "2026-03-05T08:20:05",
    completedAt: "2026-03-05T08:20:09",
    duration: 3921,
    steps: [
      { name: "API Request Alındı", status: "success", duration: 8 },
      { name: "Payload Doğrulama", status: "success", duration: 52 },
      { name: "Logo ERP Dönüşümü", status: "success", duration: 1240 },
      { name: "Agent'a İletim", status: "success", duration: 2621 },
    ],
    payload: { invoiceNo: "EFT2026000012345", amount: 18750.0 },
    errorMessage: null,
  },
  {
    id: "log004",
    tenantId: "t5",
    tenantName: "Hepsiburada.com A.Ş.",
    requestId: "REQ-20260305-004",
    type: "ORDER",
    source: "Hepsiburada API",
    status: "processing",
    startedAt: "2026-03-05T08:31:00",
    completedAt: null,
    duration: null,
    steps: [
      { name: "API Request Alındı", status: "success", duration: 11 },
      { name: "Payload Doğrulama", status: "success", duration: 40 },
      { name: "Cari Kodu Üretimi", status: "processing", duration: null },
    ],
    payload: { orderId: "HB-55443322", amount: 7800.0 },
    errorMessage: null,
  },
  {
    id: "log005",
    tenantId: "t3",
    tenantName: "Migros Ticaret A.Ş.",
    requestId: "REQ-20260304-089",
    type: "ORDER",
    source: "Trendyol API",
    status: "error",
    startedAt: "2026-03-04T23:10:02",
    completedAt: "2026-03-04T23:10:06",
    duration: 4120,
    steps: [
      { name: "API Request Alındı", status: "success", duration: 9 },
      { name: "Payload Doğrulama", status: "success", duration: 41 },
      { name: "Logo ERP Dönüşümü", status: "success", duration: 2010 },
      { name: "Agent'a İletim", status: "error", duration: 2060 },
    ],
    payload: { orderId: "TY-12345678", amount: 1299.99 },
    errorMessage: "Agent bağlantısı kesildi. Timeout (30s aşıldı).",
  },
];

// Mock users for tenant
export const mockTenantUsers = [
  {
    id: "u1",
    name: "Mehmet Yılmaz",
    email: "m.yilmaz@arcelik.com",
    role: "Tenant Admin",
    roleId: "r1",
    isActive: true,
    createdAt: "2024-01-15T10:00:00",
    lastLogin: "2026-03-05T07:45:00",
  },
  {
    id: "u2",
    name: "Selin Arslan",
    email: "s.arslan@arcelik.com",
    role: "Entegrasyon Yöneticisi",
    roleId: "r2",
    isActive: true,
    createdAt: "2024-02-01T09:00:00",
    lastLogin: "2026-03-05T08:10:00",
  },
  {
    id: "u3",
    name: "Can Yücel",
    email: "c.yucel@arcelik.com",
    role: "Sipariş Uzmanı",
    roleId: "r3",
    isActive: true,
    createdAt: "2024-03-10T11:00:00",
    lastLogin: "2026-03-04T17:30:00",
  },
  {
    id: "u4",
    name: "Burcu Kılıç",
    email: "b.kilic@arcelik.com",
    role: "Sadece İzleyici",
    roleId: "r4",
    isActive: false,
    createdAt: "2024-04-20T13:00:00",
    lastLogin: "2026-02-15T10:00:00",
  },
];

// Mock system roles
export const mockRoles = [
  {
    id: "r1",
    name: "Tenant Admin",
    description: "Tenant içindeki tüm işlemleri yönetebilir.",
    userCount: 12,
    permissions: {
      dashboard: { view: true, manage: true },
      users: { view: true, manage: true },
      logs: { view: true, manage: true },
      mappings: { view: true, manage: true },
      settings: { view: true, manage: true },
    },
  },
  {
    id: "r2",
    name: "Entegrasyon Yöneticisi",
    description: "Entegrasyon logları ve mapping ayarlarını yönetir.",
    userCount: 24,
    permissions: {
      dashboard: { view: true, manage: false },
      users: { view: true, manage: false },
      logs: { view: true, manage: true },
      mappings: { view: true, manage: true },
      settings: { view: true, manage: false },
    },
  },
  {
    id: "r3",
    name: "Sipariş Uzmanı",
    description: "Yalnızca sipariş loglarını görüntüler ve yönetir.",
    userCount: 31,
    permissions: {
      dashboard: { view: true, manage: false },
      users: { view: false, manage: false },
      logs: { view: true, manage: false },
      mappings: { view: false, manage: false },
      settings: { view: false, manage: false },
    },
  },
  {
    id: "r4",
    name: "Sadece İzleyici",
    description: "Tüm ekranları yalnızca okuma modunda görebilir.",
    userCount: 18,
    permissions: {
      dashboard: { view: true, manage: false },
      users: { view: false, manage: false },
      logs: { view: true, manage: false },
      mappings: { view: true, manage: false },
      settings: { view: false, manage: false },
    },
  },
];

// Mock mapping/rules settings for a tenant
export const mockMappingSettings = {
  tenantId: "t1",
  generalSettings: {
    autoGenerateCustomerCode: true,
    customerCodePrefix: "ARC",
    customerCodePadding: 6,
    defaultWarehouseCode: "D001",
    defaultCurrencyCode: "TRY",
    autoCreateNonExistingCustomers: true,
    syncFrequencyMinutes: 5,
  },
  orderSettings: {
    defaultOrderType: "1",
    defaultSalesman: "INTEGRASYON",
    defaultDivision: "1",
    autoApproveOrders: false,
    orderSourceMapping: {
      TRENDYOL: "TY",
      HEPSIBURADA: "HB",
      N11: "N11",
      CICEKSEPETI: "CS",
    },
  },
  invoiceSettings: {
    autoCreateInvoice: true,
    invoicePrefix: "EFT",
    defaultPaymentTerm: 30,
    vatExemptionEnabled: false,
  },
  fieldMappings: [
    { sourceField: "customer.email", targetField: "CARI_EMAIL", isActive: true, transformation: "LOWERCASE" },
    { sourceField: "customer.phone", targetField: "CARI_TELEFON", isActive: true, transformation: "FORMAT_PHONE_TR" },
    { sourceField: "order.totalAmount", targetField: "TOPLAM_TUTAR", isActive: true, transformation: "ROUND_2" },
    { sourceField: "order.shippingCost", targetField: "KARGO_TUTARI", isActive: true, transformation: "ROUND_2" },
    { sourceField: "order.discountAmount", targetField: "ISKONTO_TUTARI", isActive: false, transformation: "NONE" },
  ],
};

// Mock admin dashboard stats
export const mockAdminStats = {
  totalTenants: 6,
  activeTenants: 5,
  onlineAgents: 4,
  offlineAgents: 2,
  last24h: {
    totalTransactions: 4721,
    successfulTransactions: 4648,
    failedTransactions: 73,
    orders: 3210,
    customers: 890,
    invoices: 621,
    avgProcessingTimeMs: 2340,
  },
  weeklyTrend: [
    { day: "Pzt", success: 680, error: 12 },
    { day: "Sal", success: 720, error: 8 },
    { day: "Çar", success: 650, error: 15 },
    { day: "Per", success: 810, error: 10 },
    { day: "Cum", success: 920, error: 18 },
    { day: "Cmt", success: 490, error: 6 },
    { day: "Paz", success: 378, error: 4 },
  ],
  transactionTypes: [
    { type: "Sipariş", count: 3210, color: "bg-blue-500" },
    { type: "Cari", count: 890, color: "bg-emerald-500" },
    { type: "Fatura", count: 621, color: "bg-purple-500" },
  ],
};

// Mock tenant dashboard stats
export const mockTenantStats = {
  agentStatus: "online",
  agentVersion: "2.4.1",
  agentLastSeen: "2026-03-05T08:30:00",
  logoErpDb: "ARCELIK_PROD",
  last24h: {
    totalTransactions: 284,
    successfulTransactions: 281,
    failedTransactions: 3,
    orders: 195,
    customers: 58,
    invoices: 31,
  },
  recentActivity: [
    { time: "08:30", type: "ORDER", status: "success", ref: "TY-98765432" },
    { time: "08:25", type: "CUSTOMER", status: "error", ref: "B2B-001234" },
    { time: "08:18", type: "ORDER", status: "success", ref: "HB-77665544" },
    { time: "08:10", type: "INVOICE", status: "success", ref: "EFT2026000012341" },
    { time: "07:55", type: "ORDER", status: "success", ref: "TY-87654321" },
    { time: "07:42", type: "ORDER", status: "success", ref: "N11-11223344" },
  ],
};
